# Generated by Django 3.1.2 on 2020-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklistmodel',
            name='shared',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
