# Generated by Django 3.1.2 on 2020-10-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
        migrations.RenameField(
            model_name='tasklistmodel',
            old_name='title',
            new_name='list_title',
        ),
    ]
