# Generated by Django 3.1.2 on 2020-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task2_tasklistmodel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklistmodel2',
            name='task',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.Task2'),
        ),
    ]
