# Generated by Django 3.1.2 on 2020-11-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20201105_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task3',
            name='tasklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasklistmodel3'),
        ),
    ]
