# Generated by Django 3.1.2 on 2020-11-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title3', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.materials')),
            ],
        ),
    ]
